const websiteTranslations = {
    "aboutMeContent" : {
        "pageContent" :{
            "french" : {
                "nav" : "<li><a href=\"#\">Accueil</a></li><li><a href=\"#\" class=\"active\">à propo</a></li><li><a href=\"#\">Creations</a></li><li><a href=\"#\">Réseaux</a></li><li><a href=\"#\">Galerie</a></li><li><P>Switch language to</P><select name=\"\" id=\"selectLanguage\"><option value=\"french\"disabled selected>Français</option><option value=\"english\">English</option><option value=\"spanish\">Español</option></select></li>",
                "content" : "<div><h2>Robin888b ▪ Raven Spart</h2><p>Sallut 👋<br>Je m'appelle Robin ; je parle français et tente d'apprendre l'anglais ≈ 20%<br></p><p id=\"age\">’ai actuellement 17 ans mais j'en aurai 18 dans --- jours et -- heures.<br></p><p>J’apprends le dessin🎨 et la programmation💻<br>Que dire de plus ?<br><br>je suis un <i class=\"infolink gay\" onclick=\"toggleModal(5)\">furry</i> <i class=\"infolink gay\" onclick=\"toggleModal(4)\">gay</i> <i class=\"spoiler\" onclick=\"toggleSpoiler('sp1')\" id=\"sp1\">(mon fursona est Raven Spart)</i>, un gars très sensible et timide et un amateur de danse <i class=\"spoiler\" onclick=\"toggleSpoiler('sp2')\" id=\"sp2\">(Je pratique actuellement la danse en club 3h par semaine)</i> qui passe tout son temps à écouter de la musique</p><div class=\"sci\"><div><a href=\"https://codepen.io/Robin888b\"><img src=\"./src/img/svg/codepen.svg\" alt=\"Robin888b\" width=\"40\" height=\"30\"></a></div><div><a href=\"https://www.deviantart.com/robin888b\"><img src=\"./src/img/svg/deviant-art.svg\" alt=\"robin888b\" width=\"40\" height=\"30\"></a></div><div><a href=\"#\"><img onclick=\"toggleModal(0)\" src=\"./src/img/svg/discord.svg\" alt=\"\" width=\"40\" height=\"30\"></a></div><div><a href=\"https://www.furaffinity.net/user/robin888b/\"><img src=\"./src/img/svg/furaffinity.svg\" alt=\"furaffinity\" width=\"30\" height=\"30\"></a></div><div><a href=\"https://github.com/Robin888b\"><img src=\"./src/img/svg/github.svg\" alt=\"\" width=\"40\" height=\"30\"></a></div><div><a href=\"https://www.instagram.com/robin888b/\"><img src=\"./src/img/svg/instagram.svg\" alt=\"\" width=\"40\" height=\"30\"></a></div><div><a href=\"https://t.me/robin888b\"><img src=\"./src/img/svg/telegram.svg\" alt=\"\" width=\"40\" height=\"30\"></a></div><div><a href=\"https://www.twitch.tv/robin8888b\"><img src=\"./src/img/svg/twitch.svg\" alt=\"\" width=\"40\" height=\"30\"></a></div><div><a href=\"https://twitter.com/robin888b\"><img src=\"./src/img/svg/twitter.svg\" alt=\"\" width=\"40\" height=\"30\"></a></div><div><a href=\"https://www.youtube.com/channel/UCOqa7Ch5Y2VbgSF40RlBDyA\"><img src=\"./src/img/svg/youtube.svg\" alt=\"\" width=\"40\" height=\"30\"></a></div></div></div>",
                "title" : "Raven Spart ▪ Robin888b"
            },
            "english" : {
                "nav" : "<li><a href=\"#\">Home</a></li><li><a href=\"#\" class=\"active\">About Me</a></li><li><a href=\"#\">Creation</a></li><li><a href=\"#\">Social Links</a></li><li><a href=\"#\">Galerie</a></li><li><P>Switch language to</P><select name=\"\" id=\"selectLanguage\"><option value=\"english\" disabled selected>English</option><option value=\"french\">Français</option><option value=\"spanish\">Español</option></select></li>",
                "content" : "<div><h2>Robin888b ▪ Raven Spart</h2><p>Hello 👋<br>my name is Robin; I speak french and try to learn english ≈ 20%<br></p><p id=\"year-old\">I'm actualy 17Yo but i will be 18 in --- day and -- hours.<br></p><p>I learn to draw🎨 and program💻<br>what more to say about me ?<br><br>i'm a <i class=\"infolink gay\" onclick=\"toggleModal(1)\">gay</i> <i class=\"infolink furry\" onclick=\"toggleModal(2)\"><code>furry</code></i> <i class=\"spoiler\" onclick=\"toggleSpoiler('sp1')\" id=\"sp1\">(my fursona is Raven Spart)</i>, a Highly sensitive and shy person and a music and dance lover <i class=\"spoiler\" onclick=\"toggleSpoiler('sp2')\" id=\"sp2\">(i actualy practice dance in club 3 hours per weeks)</i></p><div class=\"sci\"><div><a href=\"https://codepen.io/Robin888b\"><img src=\"./src/img/svg/codepen.svg\" alt=\"Robin888b\" width=\"40\" height=\"30\"></a></div><div><a href=\"https://www.deviantart.com/robin888b\"><img src=\"./src/img/svg/deviant-art.svg\" alt=\"robin888b\" width=\"40\" height=\"30\"></a></div><div><a href=\"#\"><img onclick=\"toggleModal(0)\" src=\"./src/img/svg/discord.svg\" alt=\"\" width=\"40\" height=\"30\"></a></div><div><a href=\"https://www.furaffinity.net/user/robin888b/\"><img src=\"./src/img/svg/furaffinity.svg\" alt=\"furaffinity\" width=\"30\" height=\"30\"></a></div><div><a href=\"https://github.com/Robin888b\"><img src=\"./src/img/svg/github.svg\" alt=\"\" width=\"40\" height=\"30\"></a></div><div><a href=\"https://www.instagram.com/robin888b/\"><img src=\"./src/img/svg/instagram.svg\" alt=\"\" width=\"40\" height=\"30\"></a></div><div><a href=\"https://t.me/robin888b\"><img src=\"./src/img/svg/telegram.svg\" alt=\"\" width=\"40\" height=\"30\"></a></div><div><a href=\"https://www.twitch.tv/robin8888b\"><img src=\"./src/img/svg/twitch.svg\" alt=\"\" width=\"40\" height=\"30\"></a></div><div><a href=\"https://twitter.com/robin888b\"><img src=\"./src/img/svg/twitter.svg\" alt=\"\" width=\"40\" height=\"30\"></a></div><div><a href=\"https://www.youtube.com/channel/UCOqa7Ch5Y2VbgSF40RlBDyA\"><img src=\"./src/img/svg/youtube.svg\" alt=\"\" width=\"40\" height=\"30\"></a></div></div></div>",
                "title" : "Raven Spart ▪ Robin888b"
            },
            "spanish" : {
                "nav" : "<li><a href=\"#\">Inicio</a></li<li><a href=\"#\" class=\"active\">Sobre mí</a></li><li><a href=\"#\">Creación</a></li><li><a href=\"#\">redes sociales</a></li><li><a href=\"#\">Galería</a></li><li><P>Switch language to</P><select name=\"\" id=\"selectLanguage\"><option value=\"spanish\"disabled selected>Español</option><option value=\"english\">English</option><option value=\"french\">Français</option></select></li>",
                "content" : "<div><h2>Robin888b ▪ Raven Spart</h2><p>Hola 👋<br>mi nombre es Robin; hablo francés y trato de aprender inglés ≈ 20%.<br></p><p id=\"años\">Actualmente tengo 17 años, pero cumpliré 18 en --- días y -- horas.<br></p><p>Aprendo a dibujar🎨 y a programar💻<br>¿qué más decir de mí?<br><br>soy un <i class=\"infolink furry\" onclick=\"toggleModal(8)\"><code>furry</code></i> <i class=\"infolink gay\" onclick=\"toggleModal(7)\">gay</i> <i class=\"spoiler\" onclick=\"toggleSpoiler('sp1')\" id=\"sp1\">(mi fursona es Raven Spart)</i>, una persona muy sensible y tímida y amante de la música y el baile <i class=\"spoiler\" onclick=\"toggleSpoiler('sp2')\" id=\"sp2\">(actualmente practico la danza en club 3 horas por semana)</i></p><div class=\"sci\"><div><a href=\"https://codepen.io/Robin888b\"><img src=\"./src/img/svg/codepen.svg\" alt=\"Robin888b\" width=\"40\" height=\"30\"></a></div><div><a href=\"https://www.deviantart.com/robin888b\"><img src=\"./src/img/svg/deviant-art.svg\" alt=\"robin888b\" width=\"40\" height=\"30\"></a></div><div><a href=\"#\"><img onclick=\"toggleModal(0)\" src=\"./src/img/svg/discord.svg\" alt=\"\" width=\"40\" height=\"30\"></a></div><div><a href=\"https://www.furaffinity.net/user/robin888b/\"><img src=\"./src/img/svg/furaffinity.svg\" alt=\"furaffinity\" width=\"30\" height=\"30\"></a></div><div><a href=\"https://github.com/Robin888b\"><img src=\"./src/img/svg/github.svg\" alt=\"\" width=\"40\" height=\"30\"></a></div><div><a href=\"https://www.instagram.com/robin888b/\"><img src=\"./src/img/svg/instagram.svg\" alt=\"\" width=\"40\" height=\"30\"></a></div><div><a href=\"https://t.me/robin888b\"><img src=\"./src/img/svg/telegram.svg\" alt=\"\" width=\"40\" height=\"30\"></a></div><div><a href=\"https://www.twitch.tv/robin8888b\"><img src=\"./src/img/svg/twitch.svg\" alt=\"\" width=\"40\" height=\"30\"></a></div><div><a href=\"https://twitter.com/robin888b\"><img src=\"./src/img/svg/twitter.svg\" alt=\"\" width=\"40\" height=\"30\"></a></div><div><a href=\"https://www.youtube.com/channel/UCOqa7Ch5Y2VbgSF40RlBDyA\"><img src=\"./src/img/svg/youtube.svg\" alt=\"\" width=\"40\" height=\"30\"></a></div></div></div>",
                "title" : "Raven Spart ▪ Robin888b"
            }
        },



        "modalComtent" : {
            "title" : {
                "0" : "Social ⇢ Discord",
                "1" : "What is \"Gay\"",
                "2" : "What is \"Furry\"",
        
                "3" : "Résaux ⇢ Discord",
                "4" : "Que veut dire \"Gay\"",
                "5" : "Qu'est qu'un \"Furry\"",
        
                "6" : "redes sociales ⇢ Discord",
                "7" : "qué es \"Gay\"",
                "8" : "qué es \"Furry\""
            },
            "content" : {
                "0" : "<h4>Discord username : Robin888b#0423</h4><p>You can find me in <a href=\"https://discord.gg/rvUJ5cvgfX\">Curiosity</a>(french); <a href=\"https://discord.gg/d8mJrmcqdF\">Gunivers</a>(bilingual) &amp; <a href=\"https://discord.gg/discord-developers\">Discord Developers</a>(english)</p><h5>I don't accept friend requests from strangers</h5>",
                "1" : "<h4>\"gay\" means homosexual</h4><p>this term is used to describe someone who is attracted to people of the same sex, Not to people of the opposite sex like the majority</p><h5>it does not mean being more masculine or feminine and has no relation to being transgender or not</h5>",
                "2" : "<p>The word furry has several meanings, dependent on the context in which it is used. Predominantly, it means \"consisting of or resembling fur\".</p><h4>Here, it pertains to an interest in anthropomorphic animals and/or mythological or imaginary creatures which possess human or superhuman capabilities.</h4><p>The plural form of furry in all its contexts is furs or furries; the subjects of furry interest are also known as furries. Because people in the fandom tend to identify closely with their avatars (or fursonas), the word is often used to mean a group of furry characters in art or roleplay.</p>",
        
        
                "3" : "<h4>Pseudo et tag Discord : Robin888b#0423</h4> <p>Vous pouvez me trouver sur <a href=\"https://discord.gg/rvUJ5cvgfX\">Curiosity</a>(français); sur <a href=\"https://discord.gg/d8mJrmcqdF\">Gunivers</a>(bilingue) & <a href=\"https://discord.gg/discord-developers\">Discord Developers</a>(anglais) </p>",
                "4" : "<h4>\"Gay\" signifie Homosexuel</h4> <p>ce therme est utilisé pour décrir quelqu'un attiré par les personnes de même sex, pas par les personnes du sexe opposé comme la plupart des gens</p><h5>ça ne signifie pas être plus masculin ou féminin et n'a aucun rapport avec le fait d'être transgenre ou non</h5>",
                "5" : "<p>Le mot \"furry\" peut avoir plusieurs définitions dépendant du contexte; il peut signifier « constitué de fourrure » ou amas de fourrure</p><h4>Dans le cas présent, il se rapporte à une communauté portant un intérêt pour les animaux anthropomorphiques et/ou les créatures mythologiques ou imaginaires qui possèdent des capacités humaines ou surhumaines ; les furries.</h4><p>Les membre de cette communauté se créent généralement un ou plusieurs fursona, un personnage qui les représenteras dans le fandom et au quels ils s’identifient plus ou moins étroitement. Le mot est souvent utilisé pour désigner un groupe de personnages à fourrure dans l'art ou les jeux de rôle.</p>",
        
                "6" : "<h4>Nombre de usuario de Discord : Robin888b#0423</h4><p>Puedes encontrarme en <a href=\"https://discord.gg/rvUJ5cvgfX\">Curiosity</a>(francés); <a href=\"https://discord.gg/d8mJrmcqdF\">Gunivers</a>(bilingüe) &amp; <a href=\"https://discord.gg/discord-developers\">Discord Developers</a>(inglés)</p><h5>No acepto solicitudes de amistad de desconocidos</h5>",
                "7" : "<h4>\"gay\" significa homosexual</h4><p>Este término se utiliza para describir a alguien que se siente atraído por personas del mismo sexo, no por personas del sexo opuesto como la mayoría</p><h5>no significa ser más masculino o femenino y no tiene relación con ser transgénero o no</h5>",
                "8" : "<p>La palabra \"furry\" tiene varios significados, dependiendo del contexto en el que se utilice. Principalmente, significa \"que consiste o se parece a la piel\".</p><h4>En este caso, se trata de un interés por los animales antropomórficos y/o las criaturas mitológicas o imaginarias que poseen capacidades humanas o sobrehumanas.</h4><p>La forma plural de furry en todos sus contextos es furs o furries; los sujetos de interés furry también son conocidos como furries. Como la gente del fandom tiende a identificarse estrechamente con sus avatares (o fursonas), la palabra se utiliza a menudo para referirse a un grupo de personajes furries en el arte o en los juegos de rol.</p>"
            }
        }
    }
}